### ISSUE TITLE
`wait_setup` como parâmetro

### ISSUE THREAD

**Issue by Luis-Victor** [jquant/jai-sdk#77]
## Tasks:
- [x] Adicionar `wait_setup` como parâmetro do setup
- [x] Implementar a barra de progressão no método `add_data`
- [x] Adicionar `wait_setup` como parâmetro do `add_data`
- [ ] Mudar nome de `wait_setup` para `wait`

**Comment by ricardokazu** [comment]
acho que seria bom deprecar o `wait_setup` e renomear o método pra `wait`.
